name: CI:main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
jobs:
  run-tests:
    strategy:
      matrix:
        # see https://www.php.net/supported-versions.php
        php-version: ['8.2']
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install PHP (composer) dependencies
      run: composer install --prefer-dist
    - name: PHP Code style check
      run: composer fixdiff
    - name: PHP Static Analysis
      run: composer check
    - name: PHP Unit Tests
      run: composer unit_test; cat ./php-coverage/coverage.txt || echo "no coverage!"
    - name: PHP Integration Tests
      run: composer integration_test; cat ./php-coverage/coverage.txt || echo "no coverage!"

